version: '3.1'

services:

  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
    ports:
    - 3306:3306

  
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
    - 5432:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080